//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const SumEvenFibonacciSeq = (maxValue) =>{
  let addend1 = 1;
  let addend2 = 2;
  let sumOfEvenValuedTerms = 2;

  let sum = addend1 + addend2;

  while(sum < maxValue){
    addend1 = addend2;
    addend2 = sum;
    sum = addend1 + addend2;
    if(sum % 2 === 0)
      sumOfEvenValuedTerms += sum;
  }
  return sumOfEvenValuedTerms;
}

console.log("final: " + SumEvenFibonacciSeq(4000000));
